### ISSUE TITLE
ssh version really needed

### ISSUE THREAD

**Issue by mgttt** [cscott/wikipedia-telnet#12]
we are in China, you know...

**Comment by ghost** [comment]
Support, if possible.
The network of China is special. Telnet (sometimes even SSH) could be blocked. Therefore, a SSH version could be easier accessed by people live there.

**Comment by ghost** [comment]
a dedicated server for ssh and in .bash_login have a telnet to a locally hosted wikipedia-telnet server.
Ctrl-C will start a logoff though
